package.json

The npm website now allows and renders some HTML tags in package descriptions, like `<strong>` and `<a>`. The full list is here: https://www.npmjs.com/package/sanitize-html#how-to-use
`<input>` is not on the whitelist though, so it'll get stripped out. This change works around that. by using a plain English description.

remove HTML from package description

---

s3upload.js

The regular expression used to replace whitespace in filenames is incorrect; \w ends up replacing "." with "_". This change fixes mime-type detection.

Fix mime-type detection by properly replacing whitespace in filenames

---

README.md
s3router.js

This gives the ability to pass other ACL parameters i.e. `public-read`, while still being backwards compatible and falling back to `private` if no option is present.

Add option for ACL

---

README.md
ReactS3Uploader.js
s3upload.js

This adds the ability to set the Content-Disposition: header with the uploaded file's original filename. This is useful to have UUIDs as keys in S3, yet the end user still sees a familiar-looking filename.

Add option to optionally set Content-Disposition: header

---

s3upload.js

Uploading SVG files caused issues as the mime type is `image/svg+xml` and I found that when using Hapi the '+' gets stripped out.

url encode the contentType

---

README.md
package.json

but make it clear in the docs that it is required if you want to use the built in router

Remove express from the peerDependencies

---

s3upload.js

If the `xhr.responseText` is an HTML page it will fail at  `JSON.parse` and then be sent to the `onError` handler. This could result in a very large error message being rendered on the front end.

Removed xhr.responseText from onError message

---

s3upload.js

File name normalisation extended to replace all the unsafe characters by underscore.
The list of unsafe characters for file name as specified by Amazon is mentioned here:- http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html

File names with special characters not supported by Amazon handled

---

ReactS3Uploader.js

When using a minify (uglify) complains about ` getInputProps()` so i updated that line.

FIX: getInputProps fails at minify version

---

s3upload.js

Quoting the filename fixes https://github.com/odysseyscience/react-s3-uploader/issues/76
Also, the spec appears to suggest that the filename should be a quoted string: https://www.w3.org/Protocols/rfc2616/rfc2616-sec19.html#sec19.5.1

Quote Content-Disposition filename

---

ReactS3Uploader.js

If this isn't in PropTypes it causes an error as React won't accept unknown props on native elements (`input`, in this case) and it causes an error.

add scrubFilename to PropTypes

---

README.md
s3router.js

Setting `prefixName` to `false` when initializing the signing server endpoint preserves the original filename in S3.

#111 Add option to drop prefix from filenames

---

s3router.js

Is there any reason why the `filekey` isn't returned in the response body?

Return filekey

---

s3upload.js

Experienced INVALID_STATE_ERR: DOM Exception 11 while using Safari 5.1.7 on Windows 10 and signingUrlWithCredentials set to true

Fix INVALID_STATE_ERR: DOM Exception 11

---

ReactS3Uploader.js

DOM.input is deprecated and being dropped in React 16. Giving `createElement` a try locally looks to work as expected.

Fixes #127: Use createElement instead of DOM.input

---

package.json
s3router.js

The `uuid` package is unsafe, `node-uuid` is virtually identical and is the replacement. So far as I can tell, it's a drop in replacement. Trying the default configuration manually, it appears to work as expected.

Fixes #115: Use uuid instead of node-uuid

---

s3upload.js

For users who rely on header authorization in signedUrls, this enables them to add such headers to the callback of a `getSignedUrl` function

Support setting headers in signResult callback

---

ReactS3Uploader.js
s3upload.js

There are scenarios where it's useful to have a function for getting the url headers, for example when generating a short-lived authentication token.

Adding abiltiy to pass function for signingUrlHeaders

---

s3upload.js

Currently the client code rejects any response from the signing url where the status != 200. This doesn't work well with backend frameworks which use 201 for POST created success.

Enable 200 or 201 for signing success.

---

s3router.js

It's quite common for developers to want to protect their routes (especially if those routes interact with server resources like s3 buckets) with middle ware.
I love the library, but while trying to use it in a project it was not feasible out of the box as I could not use auth protected routes, rate limiting etc.
This PR allows a user to provide middle ware options to be used by the express routes.
This is my first PR in this repo so apologies if I missed any styling guidelines.

Add support to provide middle ware options to express router

---

README.md
s3router.js

This resolves #46 using what was option 3 in my last comment. I added a new parameter called getS3 which accepts a function that returns a new S3 Service Object. This leaves existing behavior of when the S3 Service Object is initialized the same while still allowing custom configuration of S3.

Add Param getS3 to allow custom S3 configuration and mocks

---

ReactS3Uploader.js

Addressing #123 and my personal pain when it comes to simplicity 😆 . While a more straightforward approach would be to simply pass in a `className` and then use `ReactDOM` to get the element with the appropriate selector, the enhancement allows the following:
```javascript
render = () => (
<ReactS3Uploader
inputRef={(el) => this.input = el}
{...otherProps} 
/>
)
```
This is especially convenient, when you're trying to support a streamlined look across all browsers like so:
```
const Container = styled.div`
&> input[type=file] {
visibility: hidden;
width: 0;
}   
`
//.... in your component:
triggerFilePicker = () => this.input.click()
render = () => (
<SomeSweetButton onClick={this.triggerFilePicker} />
<ReactS3Uplaoder
inputRef={(el) => this.input = el}
{...otherProps}
/>
)
```

Added a `inputRef` prop allowing to set `ref` on the actual input

---

s3router.js
s3upload.js

This allows a user to specify the folder a file will be uploaded to, while the file itself can be prefixed with a unique identifier.

Move uniquePrefix to be AFTER the s3path

---

README.md
ReactS3Uploader.js
s3upload.js

I have a situation where I need to handle the data returned from the signingUrl server as soon as it's available. The simplest solution I could see was to expose an onSignedUrl handler that passes back that info before uploading. I tried to make it conform to the style of all the others, so it would be a simple addition to the lifecycle handlers.

Add onSignedUrl() handler

---

s3upload.js

I was testing whether react-s3-uploader works as is when using an Azure storage container backend - and it turns out it does except for the explicit 200 check from the cloud service (aws returns 200 from the PUT, while Azure returns 201).
That is, as long as your backend signing function can provide Azure pre-signed urls (which is quite similar to azure) then this frontend component will just work with this change.
I've not added any comments about the fact that it works with Azure in the change (as you may not want to support that).
Thanks

Enable 201 response from cloud provider

---

README.md
s3router.js

Add an option to provide a custom value for the `Expires` parameter passed to `getSignedUrl`. 
In my use case, when multiple large files are uploaded at once it can take more than 60 seconds for the PUT request to actually happen causing it to come back with a 403. This problem can also happen if the signing server responds slowly because all of the signing server requests happen first making the upload PUT requests wait. Since I do not know how others use this, I did not change the default and instead added an option to change `Expires` to whatever makes sense for your application.

Add option to change when the signed upload URL expires

---

index.d.ts

Addresses more explicit response type  as well as adds a missing argument or type `File` that also gets passed in.

[CHORE] Update Argument Types

---

ReactS3Uploader.js

For cases when custom components reference ReactS3Uploader's `input` through a `React.createRef()`, for example:
```javascript
const uploaderInputRef = React.createRef();
...
<ReactS3Uploader
...
inputRef={uploaderInputRef}
/>
<button onClick={() => { uploaderInputRef.current.click(); }}>upload file</button>
```

inputRef should support React.createRef #176

---

index.d.ts

Fixes the error:
```
TS2304: Cannot find name 'S3Response'.
```

Add missing S3Response import to type definition

---

index.d.ts
package-lock.json
package.json

- fix: React was used but not imported
- fix: S3Upload extends onFinishS3Put rather than onFinish
- tweak: Add typescript & types/react dev dependencies
- tweak: Explicitly set "types" in package.json
- upload S3Upload options declared to match the ones actually used

TypeScript tweaks and fixes

---

s3upload.js

- Allow `signResult.headers` / `uploadRequestHeaders` to override `content-type`
- Allow `signResult.headers` to override `x-amz-acl`
- Allow `uploadRequestHeaders` to override `signResult.headers`
- Don't set `content-type` from `file.type` if `file.type` is not set
Previously if a header came from two places it would be given two values, which is almost never what was intended.

Custom headers fixes

---

package.json
s3upload.js

The package is using mime-type from file.type variable. But Windows machines browsers don't have it for .csv format ([source](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/ms775147(v=vs.85))).
Therefore, Content-Type for a PUT request was empty if I choose .csv files on windows. And it was throwing the error: XHR error (net::ERR_CONNECTION_RESET).
I added [mime-types](https://www.npmjs.com/package/mime-types) package and a few changes.

Find file mime type
