odysseyscience/react-s3-uploader

README.md
So I spent sometime and figured out how to get the signing part to come from a Django app. I wrote my sample code into README.md in case anyone needs it. It was pretty hard to debug by looking at AWS error messages and the not-so-stellar both documentation.
=> Added server side example code for python boto

s3upload.js
S3 throws a S3_IMPORT_NOT_FOUND error when trying to upload a file with spaces.
=> file name should support spaces

s3router.js
I turns out that I just needed to set the region for aws to get a working url, so I added the ability to specify a region in the options passed to the router.
=> Added region option for router

README.md
Thanks very much for the component, this saved me a bunch of time and helped me avoid all those jQuery plugins!
Figured this would help others - I've included posting the contentType here as I needed the headers to match on both requests :-)
Cheers!
=> Documentation to include Ruby on Rails

ReactS3Uploader.js, s3upload.js
made component more configurable by adding optional custom headers and request parameters to signing url request and to s3 upload request
=> custom headers and query parameters for request

README.md, ReactS3Uploader.js, s3router.js, s3upload.js
Updates the code so that the request to get the signed URL is CORS enabled
=> Allow request signing on cross-origin server

README.md
=> Use Markdown Code Fencing in README

README.md
The original example for Ruby on Rails crashes.
=> Fixed readme for Ruby on Rails

README.md, ReactS3Uploader.js, s3upload.js
PR addressing odysseyscience/react-s3-uploader#22. It enables to use custom routine to getSignedUrl from server.
=> Allow custom getSignedUrl functions

README.md, ReactS3Uploader.js, s3upload.js
Added onStart functionality to dynamically calculate signingQueryParams based on file selection.
=> Add onStart functionality to dynamically calculate upload file name

README.md, package.json, s3upload.js
I have removed unorm and added the default normalisation function which works as identity. It can be modified via options. I have also mildly updated the documentation.
=> BREAKING CHANGE: Removed unorm

ReactS3Uploader.js, package.json
Fixes Issue #116 
More info: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html
=> Fixing deprecations introduced in React 15.5

README.md, ReactS3Uploader.js, s3upload.js
Added s3path that receive the path where the file should be uploaded.
=> Added s3path prop

package.json
=> Remove React and ReactDOM peer dependencies

README.md
=> add micro server example

ReactS3Uploader.js
This property stops files from being automatically uploaded paving way for manual uploads.
=> Included auto upload boolean property

ReactS3Uploader.js
So if we have to access the file name there should be the third argument  in getDefaultProps: function(){}
=> In case of multiple files get name of each files with percentage

s3upload.js
In my application, I use the `onError` callback to log any upload errors to Sentry (the error logging service we use). Recently, some real errors got logged but I found them very unhelpful because they did not include any of the context from the request that was sent. In my case the PUT request was returning a 403 and I couldn't see the reason that amazon gives in their response.
This code adds relevant information about the request to each place where `onError` is called. There is no break in backwards compatibility since anyone can simply ignore the new parameter passed to `onError` callbacks.
=> Add request context to onError callback

index.d.ts
index.d.ts was missing one of the props for the component, and missing the `uploadFile` method from the `S3Upload` class.
=> Add Missing Props and Methods to index.d.ts

index.d.ts
please let me know if this needs explanation or changes!
=> Update TS types to use S3Response type for getSignedUrl
